### ISSUE TITLE
Инвентарь не открывается снова при закрытии через кнопку на экране

### ISSUE THREAD

**Issue by Vya4slav0** [Dwane-The-Rock-Johnson-game-studio/Korovany1488#13]
В юнити при нажатии I канвас с инвентарём меняет параметр активный/неактивный, но на экране больше не появляется

**Comment by ShineRookie** [comment]
починил

**Comment by ShineRookie** [comment]
Утром
- [x] Пресс качат 
- [x] Бегит
- [x] Турник
- [x] Анжуманя

Вечером
- [ ] Пресс качат 
- [ ] Бегит
- [ ] Турник
- [ ] Анжуманя
- [ ] Гантбли
